apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: edu-hopeful-ritchie
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "edu-hopeful-ritchie.sirius-k8s.dvmn.org"
  SECRET_KEY: "CHANGE-SECRET-KEY"
