apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  namespace: edu-hopeful-ritchie
  labels:
    app: django
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: anton358/django-app:c209315b94567753cb8acbd868a0ceb71dd54a1b
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py", "clearsessions"]
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: url
            envFrom:
              - configMapRef:
                  name: django-config
          restartPolicy: Never
