apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  DATABASE_URL: <base64-encoded value from django-secrets.env>
  SECRET_KEY: <base64-encoded value from django-secrets.env>
